/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_jsjni_JsJNI */

#ifndef _Included_com_iteye_weimingtom_jsjni_JsJNI
#define _Included_com_iteye_weimingtom_jsjni_JsJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iteye_weimingtom_jsjni_JsJNI_D
#define com_iteye_weimingtom_jsjni_JsJNI_D 1L
/*
 * Class:     com_iteye_weimingtom_jsjni_JsJNI
 * Method:    exec
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_jsjni_JsJNI_exec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
